import { APP_VARIANT } from "@/lib/appVariant";
import PublicPageShell from "@/components/PublicPageShell";

export default function TermsPage() {
  const name = APP_VARIANT.name;
  const isStudy = APP_VARIANT.id === "study";
  return (
    <PublicPageShell>
    <div className="space-y-8 pb-16">
      <header className="space-y-1">
        <h1 className="text-2xl font-bold">Terms of Service</h1>
        <p className="text-sm" style={{ color: "var(--muted)" }}>
          Last updated: August 2026
        </p>
      </header>

      <Section title="Agreement">
        <P>
          These terms govern your use of {name}. By creating an account or using {name}, you
          agree to them. If you don&apos;t agree, please don&apos;t use the app.
        </P>
      </Section>

      <Section title="What you get">
        <P>
          {name} is a personal life dashboard — a daily check-in, a personalised plan, and
          progress tracking across the areas you choose to follow, built for individual personal
          use. See our{" "}
          <a href="/privacy" className="underline" style={{ color: "var(--primary)" }}>
            Privacy Policy
          </a>{" "}
          for what data that involves and how it&apos;s handled.
        </P>
      </Section>

      <Section title="Your account">
        <P>
          You sign in with a one-time code sent to your email — no password to manage. You&apos;re
          responsible for keeping access to that email address secure, since it&apos;s how {name}
          verifies it&apos;s you. One account is for one person&apos;s personal use; don&apos;t
          share sign-in access or use {name} on someone else&apos;s behalf.
        </P>
      </Section>

      {isStudy && (
        <Section title="Subscription, trial, and billing">
          <P>
            {name} Plus is a paid subscription billed monthly at <strong>$4.99/month</strong> (or
            your local currency equivalent), automatically renewing until cancelled. New accounts
            get a <strong>7-day free trial</strong> of the full Plus experience — no charge during
            the trial. If you don&apos;t cancel before the trial ends, and haven&apos;t started a
            subscription, {name} simply drops you to the free tier — you are never automatically
            charged just because a trial lapsed.
          </P>
          <P>
            Payment is processed by <strong>Stripe</strong> (web) or <strong>Google Play
            Billing</strong> via <strong>RevenueCat</strong> (Android app). We don&apos;t see or
            store your full card details. You can cancel anytime from {name}&apos;s billing
            settings (web, via Stripe&apos;s customer portal) or through Google Play&apos;s
            subscription management (Android) — cancelling stops future renewals but doesn&apos;t
            refund the current billing period. Access continues until the end of the period
            you&apos;ve already paid for.
          </P>
          <P>
            The free tier is a real, complete product on its own — one area, a 7-day view, no
            calendar sync — not a crippled trial. You can use it indefinitely without ever
            subscribing.
          </P>
        </Section>
      )}

      <Section title="Google Calendar connection">
        <P>
          If you connect Google Calendar, you&apos;re granting {name} read-only access to display
          your events and avoid scheduling conflicts, as described in our Privacy Policy. You can
          disconnect this at any time from within {name} or from your Google account&apos;s
          permissions page — doing so doesn&apos;t affect your {name} account otherwise.
        </P>
      </Section>

      <Section title="Acceptable use">
        <P>You agree not to:</P>
        <ul className="mt-2 space-y-1.5 text-sm" style={{ color: "var(--muted)" }}>
          {[
            "Use the app for anything unlawful, or to violate anyone else's rights",
            "Attempt to access another user's account or data",
            "Interfere with or disrupt the app's infrastructure",
            "Reverse-engineer the app to circumvent the subscription gate",
          ].map((item) => (
            <li key={item} className="flex gap-2">
              <span style={{ color: "var(--primary)" }}>·</span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </Section>

      <Section title="No professional advice">
        <P>
          {name} is a personal organisation tool. It doesn&apos;t provide medical, fitness,
          academic, financial, or other professional advice
          {isStudy && ", including anything generated by its optional AI coach feature"}. Use your
          own judgement, and consult a qualified professional for decisions that need one.
        </P>
      </Section>

      <Section title="Availability and changes">
        <P>
          {name} is provided on an &quot;as is&quot; basis. We aim for high availability but
          don&apos;t guarantee the app will always be uninterrupted or error-free. We may update
          or change features over time; if a change materially affects your subscription, we&apos;ll
          make reasonable efforts to let you know in advance.
        </P>
      </Section>

      <Section title="Termination">
        <P>
          You can stop using {name} and delete your account at any time by contacting us. We may
          suspend or terminate accounts that violate these terms, misuse the service, or where
          required by law.
        </P>
      </Section>

      <Section title="Liability">
        <P>
          To the extent permitted by law, {name} and its developer aren&apos;t liable for indirect
          or consequential damages arising from your use of the app. Nothing here limits liability
          that can&apos;t be excluded under applicable law.
        </P>
      </Section>

      <Section title="Changes to these terms">
        <P>
          We may update these terms as the app evolves. Continuing to use {name} after a change
          means you accept the updated terms. We&apos;ll update the &quot;Last updated&quot; date
          above whenever that happens.
        </P>
      </Section>

      <Section title="Contact">
        <P>
          Questions about these terms:{" "}
          <a
            href={`mailto:${APP_VARIANT.supportEmail}`}
            className="underline"
            style={{ color: "var(--primary)" }}
          >
            {APP_VARIANT.supportEmail}
          </a>
        </P>
      </Section>
    </div>
    </PublicPageShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-base font-semibold">{title}</h2>
      <div className="space-y-2">{children}</div>
    </section>
  );
}

function P({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <p className={`text-sm leading-relaxed ${className}`} style={{ color: "var(--muted)" }}>
      {children}
    </p>
  );
}
